### ISSUE TITLE
搜索界面-文档分组：分组结果没有正确的缩进

### ISSUE THREAD

**Issue by frostime** [chenshinshi/zhang-light#2]
![image](https://github.com/chenshinshi/zhang-light/assets/27268127/37d9cc21-3acc-4a2d-9fe8-4315f8a0477c)

按照文档分组组织搜索结果后，各个文档下的搜索结果没有正确的缩进到文档下档。

**Comment by chenshinshi** [comment]
收到，下个版本修复
