### ISSUE TITLE
能否更换掉标题的线条

### ISSUE THREAD

**Issue by takeiteasyman** [chenshinshi/zhang-light#4]
![image](https://github.com/chenshinshi/zhang-light/assets/45447994/afe318fd-0d0f-4194-8680-1a699aacf9a8)
当标题过长的时候，线条跟不上，反而影响美观。能否删除或更换为其他点缀

十分喜欢标题自动编号，但是能否对各级标题的字体大小有所区分？其次，按照章、节、一设计或许来源于学位论文的标题设计，颜色上是否能朴素一点？颜色过多使得与常规学位论文一时间不能很好的接受。

**Comment by chenshinshi** [comment]
抱歉，因为zhang-light主题是他人的设计，我这边是不好去做bug以外的改动的。
